// <auto-generated />
using EFCore.ParadeDB.PgSearch.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.ParadeDB.PgSearch.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415140018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_search");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCore.ParadeDB.PgSearch.Api.Persistence.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "A vintage leather journal featuring hand-stitched binding, aged parchment pages, and a brass clasp closure.\nEach page has a subtle texture that makes writing a tactile pleasure, and the cover develops a rich patina over time.\nPerfect for travelers, writers, and anyone who appreciates the art of analog note-taking.",
                            Name = "Vintage Leather Journal"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "A premium bamboo cutting board with a deep juice groove along the perimeter to catch liquids during food prep.\nFeatures a built-in herb stripper, a hanging hole for easy storage, and a non-slip base to keep it firmly in place.\nNaturally antimicrobial and gentle on knife edges, making it an essential kitchen companion.",
                            Name = "Bamboo Cutting Board"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "A handcrafted ceramic pour-over coffee dripper paired with a solid walnut stand and a reusable stainless mesh filter.\nThe carefully angled interior ribs slow the flow rate for optimal extraction, producing a clean and nuanced cup.\nDesigned for coffee enthusiasts who treat their morning brew as a ritual rather than a routine.",
                            Name = "Ceramic Pour-Over Coffee Dripper"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "A ultra-soft Merino wool travel blanket that folds and compresses neatly into its own integrated carry pouch.\nNaturally temperature-regulating and odor-resistant, it keeps you warm on cold flights and cool in mild conditions.\nLightweight enough to slip into a carry-on, yet substantial enough to replace a full-size throw at home.",
                            Name = "Merino Wool Travel Blanket"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "A solar-powered desk lamp with a flexible gooseneck arm, adjustable color temperature ranging from warm amber to cool daylight,\nand a built-in USB-A charging port to keep your devices powered throughout the day.\nThe wide solar panel charges efficiently even in indirect light, making it ideal for eco-conscious home and office setups.",
                            Name = "Solar-Powered Desk Lamp"
                        });
                });

            modelBuilder.Entity("EFCore.ParadeDB.PgSearch.Api.Persistence.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Experience unparalleled comfort with the UltraComfort Memory Foam Running Shoes.\nDesigned for athletes and casual joggers alike, these shoes feature a breathable mesh upper,\na cushioned memory foam insole that molds to your foot's unique shape, and a durable rubber outsole.\nWhether you're hitting the pavement or enjoying a leisurely walk, these shoes provide the support\nand comfort you need.",
                            Name = "UltraComfort Memory Foam Running Shoes"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Elevate your running experience with the ProStride Jogging Sneakers.\nCrafted with a lightweight, breathable mesh upper, these sneakers offer optimal ventilation\nto keep your feet cool. The responsive cushioning system absorbs impact, reducing strain on your joints,\nwhile the slip-resistant rubber outsole ensures stability on various surfaces.\nPerfect for both seasoned runners and beginners.",
                            Name = "ProStride Jogging Sneakers"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Immerse yourself in high-quality sound with the NoiseCancel Wireless Headphones.\nFeaturing advanced noise-cancelling technology, these headphones block out ambient noise,\nallowing you to focus on your music or calls. The ergonomic design ensures a comfortable fit\nfor extended wear, and the long-lasting battery provides hours of uninterrupted listening.\nIdeal for travel, work, or leisure.",
                            Name = "NoiseCancel Wireless Headphones"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Discover exceptional audio clarity with the StudioSound Over-Ear Headphones.\nEquipped with premium drivers, these headphones deliver rich bass and crisp highs,\nproviding an immersive listening experience. The plush ear cups and adjustable headband\noffer a personalized fit, while the foldable design makes them easy to store and transport.\nSuitable for audiophiles and casual listeners alike.",
                            Name = "StudioSound Over-Ear Headphones"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Brew your favorite coffee with the EcoBrew French Press Coffee Maker.\nMade from high-quality borosilicate glass and stainless steel, this French press ensures durability\nand heat retention. The fine mesh filter allows essential oils and fine particles to pass through,\ndelivering a rich and full-bodied cup of coffee. Its sleek design and easy-to-use mechanism\nmake it a must-have for coffee enthusiasts.",
                            Name = "EcoBrew French Press Coffee Maker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
