// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParadeDB.EFCore.IntegrationTests.Persistence;

#nullable disable

namespace ParadeDB.EFCore.IntegrationTests.Persistence.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20260511201853_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_search");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParadeDB.EFCore.IntegrationTests.Persistence.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("Id", "Description", "Name")
                        .HasDatabaseName("ix_items_id_description_name")
                        .HasAnnotation("Npgsql:StorageParameter:key_field", "id")
                        .HasAnnotation("ParadeDb:ColumnTokenizers", new[] { null, "pdb.simple('alias=description_simple')", null });

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Id", "Description", "Name"), "bm25");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("ParadeDB.EFCore.IntegrationTests.Persistence.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Id", "Description", "Name")
                        .HasDatabaseName("ix_products_id_description_name")
                        .HasAnnotation("Npgsql:StorageParameter:key_field", "id")
                        .HasAnnotation("ParadeDb:AdditionalIndexExpressions", new[] { "((details->>'Summary')::pdb.literal('alias=details_summary'))", "((details->>'Summary')::pdb.icu('alias=details_summary_icu'))", "((details->>'Tags')::pdb.icu('alias=details_tags'))" });

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Id", "Description", "Name"), "bm25");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ParadeDB.EFCore.IntegrationTests.Persistence.Entities.Product", b =>
                {
                    b.OwnsOne("ParadeDB.EFCore.IntegrationTests.Persistence.Entities.ProductDetails", "Details", b1 =>
                        {
                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string[]>("Tags")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.ToJson("details");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
